# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

# Travis whitelists the packages we can install, we can request additions
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages: &common_deps
      - ccache
      - gfortran
      - libatlas-base-dev
      - libatlas-dev
      - liblapack-dev
      # Speedup builds, particularly when USE_CHROOT=1
      - eatmydata

      # chroot dependencies
      #- g++-multilib
      #- gcc-multilib
      #- gfortran-multilib
      #- fakechroot
      #- fakeroot Already installed
#      - libc6:i386
#      - libatlas-base-dev:i386
#      - libatlas-dev:i386
#      - liblapack-dev:i386
#      - libncurses:i386
#      - libstdc++6:i386
      # - pbuilder

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.5-dev
matrix:
  include:
    - python: 3.3
      env: USE_CHROOT=1 ARCH=i386 DIST=trusty PYTHON=3.4
      sudo: true
      addons:
        apt:
          packages:
            - *common_deps
            - debootstrap
    - python: 3.2
      env: USE_DEBUG=1
      addons:
        apt:
          packages:
           - *common_deps
           - python3-dbg
           - python3-nose
    - python: 2.7
      env: NPY_SEPARATE_COMPILATION=0 PYTHON_OO=1
    - python: 3.4
      env: NPY_RELAXED_STRIDES_CHECKING=0
    - python: 2.7
      env: USE_BENTO=1
    - python: 2.7
      env: USE_WHEEL=1
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Build into own virtualenv
  # We therefore control our own environment, avoid travis' numpy
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -V
  - pip install --upgrade pip setuptools
  # Dependencies & wheels are cached by pip as they're downloaded & built
  - pip install -r ../dev-requirements.txt
  - pip install Cython --install-option="--no-cython-compile"
  - popd

script:
  - ./tools/travis-test.sh
