# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

# Travis restricts these packages to a whitelist, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages:
      #- g++-multilib
      #- gcc-multilib
      - gfortran
      #- gfortran-multilib
      - libatlas-base-dev
#      - libatlas-base-dev:i386
      - libatlas-dev
#      - libatlas-dev:i386
      - liblapack-dev
#      - liblapack-dev:i386
      # USE_DEBUG dependencies
      - python3-dbg
      - python3-nose
      # chroot dependencies
      #- debootstrap
      - eatmydata
      #- fakechroot
      #- fakeroot Already installed
#      - libc6:i386
#      - libncurses:i386
#      - libstdc++6:i386
      # - pbuilder

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.5-dev
matrix:
  include:
#    - python: 3.3
#      env: USE_CHROOT=1 ARCH=i386 DIST=trusty PYTHON=3.4
    - python: 3.2
      env: USE_DEBUG=1
    - python: 2.7
      env: NPY_SEPARATE_COMPILATION=0 PYTHON_OO=1
    - python: 3.4
      env: NPY_RELAXED_STRIDES_CHECKING=0
    - python: 2.7
      env: USE_BENTO=1
    - python: 2.7
      env: USE_WHEEL=1
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  # Build into own virtualenv
  # We therefore control our own environment, avoid travis' numpy
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -V
  - pip install --upgrade pip setuptools
  # Dependencies & wheels are cached by pip as they're downloaded & built
  - pip install -r ../dev-requirements.txt
  - pip install Cython --install-option="--no-cython-compile"
  - popd

script:
  - ./tools/travis-test.sh
